config/routes.rb
Rails.application.routes.draw do
  resources :invite_codes, only: [:create, :new, :index, :edit, :update, :destroy]
  resources :guests

  root 'application#home'
  get '/information', to: 'application#information'

  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show, :edit, :update]

  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  validates :last_name, :first_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name, case_sensitive: false,
    message: 'and last name are already in use by a user who has signed up'}
  validate :guest_count, on: :create
  validate :guest_name

  default_scope { order(last_name: :asc) }

  belongs_to :user

  def self.below_drinking_age
    Guest.where(below_drinking_age: true).count
  end

  def name
    "#{first_name} #{last_name}"
  end

  def allowed_guests
    0
  end

  def guest_name
    return unless User.find_by(first_name: first_name, last_name: last_name)
    self.errors.add(:base, 'a guest may not have the same name as another user')
  end

  def guest_count
    # self.errors.add(:base, 'your guest count has been reached') unless user.can_invite_guest?
    true
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
    @users = User.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        redirect_url = current_user.admin? ? guests_url : edit_user_registration_path
        format.html { redirect_to redirect_url, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        redirect_url = current_user.admin? ? guests_url : edit_user_registration_path
        format.html { redirect_to redirect_url, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    redirect_url = current_user.admin? ? guests_url : edit_user_registration_path
    respond_to do |format|
      format.html { redirect_to redirect_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_guest
    @guest = Guest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def guest_params
    params['guest']['user_id'] = current_user.id
    params['guest'].permit(:last_name, :first_name, :food_preference, :user_id,
      :below_drinking_age, :role, :hotel, :allergy)
  end
end

app/views/guests/_form.html.haml
= form_for @guest do |f|
  - if @guest.errors.any?
    #error_explanation
      %h2= "#{pluralize(@guest.errors.count, "error")} prohibited this guest from being saved:"
      %ul
        - @guest.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :first_name
    = f.text_field :first_name, autofocus: true
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :food_preference
    = f.select :food_preference, User.food_preferences.keys, { include_hidden: false, include_blank: 'None' }, id: 'restriction'
  .field{id: 'allergy'}
    = f.label :allergy do
      Food Allergies or Restrictions
    = f.text_area :allergy
  .field.switch.large
    = f.label :below_drinking_age
    = f.check_box :below_drinking_age, class: 'hide'
    %label.switch-paddle{for: 'guest_below_drinking_age'}
      %span.switch-active{'aria-hidden' => 'true'} Yes
      %span.switch-inactive{'aria-hidden' => 'true'} No
  .actions
    = f.submit 'Save', class: 'button success float-left'

app/views/guests/edit.html.haml
%h1= "Editing #{@guest.name}"

= render 'form'
= link_to 'Back', guests_path, class: 'button float-right'

app/views/guests/index.html.haml
%h3 Summary

%table
  %thead
    %tr
      %th Signups
      %th RSVPs
      %th Hotel Rooms
      %th Non-Drinkers

  %tbody
    %tr
      %td= @guests.count + User.count
      %td= User.coming
      %td= User.hotel_rooms
      %td= Guest.below_drinking_age

%h3 Guest List
%table
  %thead
    %tr
      %th Name
      %th Food Preference
      %th Allergy
      %th Actions

  %tbody
    - @guests.each do |guest|
      %tr
        %td= link_to guest.name, guest_path(guest)
        %td= guest.food_preference
        %td= guest.allergy
        %td.actions
          %ul
            %li
              = link_to edit_guest_path(guest), class: 'button warning' do
                %i.fa.fa-pencil-square-o
            %li
              = link_to guest, class: 'button alert', method: :delete, data: { confirm: 'Are you sure?' } do
                %i.fa.fa-trash

= link_to 'New Guest', new_guest_path, class: 'button'

%h3 User List

%table
  %thead
    %tr
      %th Name
      %th Role
      %th Email
      %th Hotel
      %th Hotel Rooms
      %th RSVP
      %th Allowed Guests
      %th Last Sign In
      %th Sign In Count
      %th Actions

  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.name, user_path(user)
        %td= user.role
        %td= user.email
        %td= user.hotel
        %td= user.try(:hotel_rooms) || 0
        %td
          %ul
            %li
              - if user.try(:rsvp)
                %i.fa.fa-check
              - else
                %i.fa.fa-times
        %td= user.allowed_guests
        %td= user.last_sign_in_at
        %td= user.sign_in_count
        %td.actions
          %ul
            %li
              = link_to edit_user_path(user), class: 'button warning' do
                %i.fa.fa-pencil-square-o
            %li
              = link_to admin_destroy_user_path(user), class: 'button alert', method: :delete, data: { confirm: 'Are you sure?' } do
                %i.fa.fa-trash

  %table
    %thead
      %tr
        %th Email

    %tbody
      - @users.each do |user|
        %tr
          %td= user.email

app/views/guests/new.html.haml
%h1 New Guest

= render 'form'

= link_to 'Back', guests_path, class: 'button float-right'

app/views/guests/show.html.haml
%p#notice= notice

%h1= @guest.name

= @guest.allergy
= @guest.food_preference
= @guest.user.name

= link_to 'Edit', edit_guest_path(@guest), class: 'button'
= link_to 'Back', guests_path, class: 'button'