config/routes.rb
Rails.application.routes.draw do
  resources :invite_codes, only: [:create, :new, :index, :edit, :update, :destroy]
  resources :guests

  root 'application#home'
  get '/information', to: 'application#information'

  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show, :edit, :update]

  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
end

app/models/invite_code.rb
class InviteCode < ActiveRecord::Base
  has_many :users

  default_scope { order(guests: :asc) }

  before_destroy :not_in_use

  protected

  def not_in_use
    if User.where(invite_code_id: id)
      self.errors.add(:base, 'invite code is in use and cannot be deleted')
      false
    end
  end
end

app/controllers/invite_codes_controller.rb
class InviteCodesController < ApplicationController
  before_action :set_invite_code, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /invite_codes
  def index
    @invite_codes = InviteCode.all
  end

  # GET /invite_codes/new
  def new
    @invite_code = InviteCode.new
  end

  # GET /invite_codes/1/edit
  def edit
  end

  # POST /invite_codes
  def create
    @invite_code = InviteCode.new(invite_code_params)

    if @invite_code.save
      redirect_to invite_codes_url, notice: 'Invite code was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /invite_codes/1
  def update
    if @invite_code.update(invite_code_params)
      redirect_to invite_codes_url, notice: 'Invite code was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /invite_codes/1
  def destroy
    @invite_code.destroy
    redirect_to invite_codes_url, notice: 'Invite code was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invite_code
    @invite_code = InviteCode.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def invite_code_params
    params['invite_code'].permit(:value, :guests)
  end
end

app/views/invite_codes/_form.html.haml
= form_for @invite_code do |f|
  - if @invite_code.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invite_code.errors.count, "error")} prohibited this invite_code from being saved:"
      %ul
        - @invite_code.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :value
    = f.text_field :value, autofocus: true
  .field
    = f.label :guests
    = f.number_field :guests

  .actions
    = f.submit 'Save', class: 'button success float-left'

app/views/invite_codes/edit.html.haml
%h1 Editing Invite Code

= render 'form'

= link_to 'Back', invite_codes_path, class: 'button float-right'

app/views/invite_codes/index.html.haml
%h1 Invite Codes

%table
  %thead
    %tr
      %th Code Value
      %th Guests
      %th Users
      %th Actions

  %tbody
    - @invite_codes.each do |invite_code|
      %tr
        %td= invite_code.value
        %td= invite_code.guests
        %td
          %ul
          - invite_code.users.each do |user|
            %li= link_to user.name, user_path(user)
        %td.actions
          %ul
            %li
              = link_to edit_invite_code_path(invite_code), class: 'button warning' do
                %i.fa.fa-pencil-square-o
            %li
              = link_to invite_code, class: 'button alert', method: :delete, data: { confirm: 'Are you sure?' } do
                %i.fa.fa-trash

= link_to 'New invite code', new_invite_code_path, class: 'button'

app/views/invite_codes/new.html.haml
%h1 New Invite Code

= render 'form'

= link_to 'Back', invite_codes_path, class: 'button float-right'