config/routes.rb
Rails.application.routes.draw do
  resources :invite_codes, only: [:create, :new, :index, :edit, :update, :destroy]
  resources :guests

  root 'application#home'
  get '/information', to: 'application#information'

  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show, :edit, :update]

  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
end

app/views/layouts/application.html.haml
!!! 5
%html.no-js{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}/
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}/
    %title Very Boveri
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tag
    = favicon_link_tag 'wedding-couple.png'

  %body
    #example-menu.top-bar
      .top-bar-left
        %ul.dropdown.menu{'data-dropdown-menu' => ''}
          %li
            = link_to root_path, class: 'faa-parent animated-hover' do
              %i.fa.fa-heart.faa-pulse
          - if user_signed_in? && current_user.admin
            %li= link_to 'Guests', guests_path
            %li= link_to 'Invite Codes', invite_codes_path
      .top-bar-right.float-right.profile-menu
        - if user_signed_in?
          %ul{'data-dropdown-menu' => ''}
            %li
              %i.fa.fa-user.fa-inverse.fa-2x
              %ul.menu
                %li= link_to 'Edit profile', edit_user_registration_path
                %li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %ul.menu
            %li= link_to 'Find out more', information_path
            %li= link_to 'Sign up', new_user_registration_path
            %li= link_to 'Login', new_user_session_path
    - if controller.action_name == 'home'
      = yield
    - else
      .row.top-row
        .large-12.small-centered.columns
          = yield

    = stylesheet_link_tag 'font-awesome-animation.css'
    :javascript
      $(document).ready(function() {
        $(document).foundation();
      });